[project]
name = "sih"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nash504", email = "nashdfern@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pymongo>=4.15.0",
    "python-dotenv>=1.0.0",
    "twilio>=9.8.0",
]

[project.scripts]
sih = "sih:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
